### ISSUE TITLE
RIG should run as non-root user in container

### ISSUE THREAD

**Issue by chadmott** [Accenture/reactive-interaction-gateway#316]
## Summary and context

I would hope to be able to run the streaming gateway with least privilege, but when I restrict privileges in k8s yaml, the RIG will not run

## How to reproduce

run in a k8s cluster:
```yaml  
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
```

If you run this, you will get an error:
```
 kubelet, docker-desktop  Error: container has runAsNonRoot and image will run as root
```
if you comment out `runAsNonRoot` (keeping the other securityContext settings) you still get an error
```
kubectl logs ->
mkdir: can't create directory '/opt/sites/rig/var': Permission denied
```

If you run RIG without these configs, I see this in Popeye (a k8s scanning tool)

```
  · default/streaming-gateway-848c8545f7-582kh.....................................................😱
    😱 [POP-302] Pod could be running as root user. Check SecurityContext/image.
    🐳 reactive-gateway
      😱 [POP-306] Container could be running as root user. Check SecurityContext/Image.
```
> Describe whether you use Docker or not, the environment variables you set and the config files you use.

Docker/k8s (see above)

> Describe how your clients are set up, whether they connect via SSE or WS, etc.

**..but I really expected this:**

RIG to run as non-root user, with these group/user permissions.

## Versions (please complete the following information):**

 - Host OS: Mac/Docker for Desktop/K8s 1.16.5
 - Frontend n/a
 - RIG version as shown on startup Reactive Interaction Gateway 2.4.0 [rig@10.1.16.177, ERTS 10.7.2.1, OTP 22]

**Comment by Knappek** [comment]
Thanks @chadmott for reporting this. That should not be the case. I'll look into this.

**Comment by Knappek** [comment]
@chadmott I've created the PR #317 which allows running rig with the following `securityContext`: 

```yaml
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
```

Do you think this is this fine?
