### ISSUE TITLE
Scaling Rig with Helm Chart

### ISSUE THREAD

**Issue by AcidLeroy** [Accenture/reactive-interaction-gateway#332]
## Summary and context

When running RIG with the provided Helm chart, RIG nodes do not behave as if they are connected. When publishing events to a three node RIG cluster, a subscriber will only receive 1/3 of the messages. 

## How to reproduce

**When I run RIG with these settings:**
```bash 
git clone git@github.com:Accenture/reactive-interaction-gateway.git
cd reactive-interaction-gateway/deployment/reactive-interaction-gateway
helm install rig .
helm upgrade --set replicaCount=3 rig .
```

I also setup an ingress: 
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rig
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - secretName: ingress-default-cert
      hosts:
        - "mydns.name.com"
  rules:
  - host: "mydns.name.com"
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: rig-reactive-interaction-gateway-headless
          servicePort: 4010
      - path: /rig(/|$)(.*)
        pathType: Prefix
        backend:
          serviceName: rig-reactive-interaction-gateway-headless
          servicePort: 4000
```

Next I have a client setup like this: 

```js
const EventSource = require('eventsource');
const fetch = require('node-fetch'); 

const host = "https://mydns.name.com/rig"
const endpoint=`${host}/_rig/v1/connection/sse`

var source = new EventSource(endpoint)
source.onopen = (e) => console.log("open", e)
source.onmessage = (e) => console.log("message", e)
source.onerror = (e) => console.log("error", e)

let count = 0; 

source.addEventListener('pulse', e => {
    // console.log(e.data)
    count++; 
    console.log(`id = ${e.data}, count = ${count}`)
})

source.addEventListener("error", function (e) {
    if (e.readyState == EventSource.CLOSED) {
      console.log("Connection was closed.")
    } else {
      console.log("Connection error:", e)
    }
  }, false);

source.addEventListener("rig.connection.create", async function (e) {
    let cloudEvent = JSON.parse(e.data)
    let payload = cloudEvent.data
    let connectionToken = payload["connection_token"]
    console.log('cloudEvent ', cloudEvent); 
    console.log('connection Token = ', connectionToken); 
    let res = await createSubscription(connectionToken)
    let text = await res.text()
    console.log('DONE===> ', text)
 
  }, false);

function createSubscription(connectionToken) {
    const eventType = "pulse"
    const token = connectionToken; 
    const route=`${host}/_rig/v1/connection/sse/${token}/subscriptions`; 
    console.log('route = ', route); 
    return fetch(route, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            "subscriptions": [{
            "eventType": eventType
            }]
        })
    })
}
  
```

and finally my publisher: 

```js
const fetch = require('node-fetch'); 
const host = "https://mydns.name.com/rig"

// helm upgrade --set replicaCount=1 rig accenture/reactive-interaction-gateway
function startPublisher(){

    let id = 0; 
    async function publish() {
        let message = {
            specversion: "0.2", 
            id: id, 
            type: "pulse"
        }
        id = id + 1; 
        let p =  await fetch(`${host}/_rig/v1/events`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(message)
        })

        console.log('Published: ', id);
        
    }

    setInterval(publish, 500); 
}

```

After running the client, and then publisher, you should notice that approximately 1/3 of messages are being received. Additionally, you will see that getting the connection token is problematic because the request and then subscription get routed to different nodes. Is this expected behavior, or should the nodes be communicating with each other? 

Here is an example of the log output that I am receiving on one of the nodes: 
```
21:10:27.900 module=Peerage.Server [debug] [Peerage 1.0.3][ Elixir.Peerage.Via.Dns] Discovery every 5s.

     NAME                RESULT OF ATTEMPT

     LIVE NODES
     rig@XX.XX.3.8 (self)

21:10:28.918 module=Plug.Logger request_id=Fj34GQ6vql1pJ3oAAAM_ [info] GET /health
21:10:28.918 module=Phoenix.Logger request_id=Fj34GQ6vql1pJ3oAAAM_ [debug] Processing with RigApi.Health.check_health/2
  Parameters: %{}
  Pipelines: [:body_parser]
21:10:28.918 module=Plug.Logger request_id=Fj34GQ6vql1pJ3oAAAM_ [info] Sent 200 in 111µs
```

The output above shows that my nodes never find each other. 

Additionally, I checked the DNS_NAME in my nodes, and they are set to: `rig-reactive-interaction-gateway-headless.default.svc.cluster.local`

Is there a way to do a quick sanity check to see why Peerage doesn't seem to work? 

## Versions (please complete the following information):**
 - Reactive Interaction Gateway 3.0.0-alpha.1
